# ===================================================================
# Activate this profile to enable TLS and HTTP/2.
# ===================================================================
server:
    ssl:
        key-store: classpath:config/tls/keystore.p12
        key-store-password: password
        key-store-type: PKCS12
        key-alias: selfsigned
jhipster:
    http:
        version: V_2_0
